/**
 * English resources for the admin. EN + ES with a device-default and a
 * language selector (reverts the old "admin is English-only" convention).
 * Every key here MUST have an ES counterpart in `es.ts` — the parity test
 * (`src/__tests__/i18nParity.test.ts`) fails on any drift.
 */
export default {
  common: {
    close: 'Close',
  },
  language: {
    label: 'Language',
    english: 'English',
    spanish: 'Spanish',
    a11y: 'Change language',
  },
  nav: {
    curationQueue: 'Curation Queue',
    analytics: 'Analytics',
    editPlace: 'Edit Place',
    createPlace: 'Create Place',
    createPlan: 'Create Plan',
    editPlan: 'Edit Plan',
    importGoogle: 'Import from Google',
  },
  analytics: {
    ranges: {
      '7d': '7d',
      '30d': '30d',
      '90d': '90d',
      '1y': '1y',
      all: 'All',
    },
    error: {
      failed: 'Failed to load analytics: {{error}}',
      retry: 'Retry',
    },
    truncated:
      'Large range: the summary cards stay exact, but the series, percentiles and mixes use the {{rows}} most recent rows. For All-time and very large ranges the chart starts at the oldest of those rows, so older history may be missing entirely.',
    chat: {
      title: 'Chat',
      turns: 'Turns',
      cost: 'Cost (range)',
      latencyP50: 'Latency p50',
      latencyP95Hint: 'p95 {{value}}',
      errorRate: 'Error rate',
      slotCompleteness: 'Slot completeness (avg)',
      turnsPerPeriod: 'Turns / period',
      providerModel: 'Provider · model',
      finishReasons: 'Finish reasons',
      errorCodes: 'Error codes',
      empty: 'No chat turns in this range.',
    },
    plans: {
      title: 'Plans',
      generated: 'Plans generated',
      avgCost: 'Avg cost / plan',
      opened: 'Opened',
      followed: 'Followed',
      plansBySource: 'Plans / period by source',
      byCity: 'By city',
      empty: 'No plans generated in this range.',
    },
    cityTable: {
      city: 'City',
      count: 'Plans',
      opened: 'Opened',
      followed: 'Followed',
      empty: 'No plans in this range.',
    },
    legend: {
      a11y: 'What {{metric}} measures',
      turns: 'Messages processed by the AI chat. Measures the volume of the conversational flow.',
      cost: 'Spend on AI tokens. The variable cost of the chat.',
      latency: 'Half of turns answer under p50; p95 is the slow tail. Reflects the experience and provider degradation.',
      errorRate: 'Percentage of failed turns. Measures the health of the AI pipeline.',
      slotCompleteness: 'How many of the 9 preferences the conversation extracts on average. Shows whether it gathers enough to generate a plan.',
      turnsPerPeriod: 'How turn volume evolves over the period.',
      providerModel: 'Split by the LLM that answered each turn. Shows how often the fallback kicks in.',
      finishReasons: 'The reason each model turn finished with. Helps spot truncation or filtered answers.',
      errorCodes: 'Failed turns broken down by error code. Pinpoints the cause of the failures.',
      plansGenerated: 'Itineraries generated by the AI.',
      avgCost: 'AI cost per generated plan. The unit cost.',
      opened: 'Percentage of generated plans that were opened. Signals whether the plan drew interest.',
      followed: 'Percentage of plans that went into Follow Mode. A strong signal of value.',
      plansBySource: 'Plans per period by their origin (wizard vs chat).',
      byCity: 'Volume and quality (opened, followed) per city.',
    },
  },
} as const;
